### ISSUE TITLE
Những lỗi cần phải sửa

### ISSUE THREAD

**Issue by harrytran998** [lalala345/express-sql-api#3]
1. Biến không dùng đến => Xoá đi

Trong file `user.router.js` thừa `q`
```js
const q = req.query.q
```
2. Không đồng nhất cách đặt tên folder
- Tất cả folder đang ở dạng calmelCase or snakeCase => Sao lòi ra 1 folder là `DB`
3. 2 file là `places.router.js` và `user.router.js` đã nằm trong folder router rồi mà vẫn đặt tên như thế => Chỉ cần `Places.js'  vs `User.js` là OK rồi!

**Comment by lalala345** [comment]
fixed
